### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by chris-pb** [InfotelGLPI/certificates#11]
Hi, i tried to upgrade the plugin from Version 2.2.0 to Version 2.2.1 in a glpi 9.1.6 instance but nothing happens.
I didn't see the upgrade link after updating the directory files with the new version

The plugin stay in Version 2.2.0 and is still working.

Regards

Christophe

**Comment by amma35** [comment]
Indeed, a version error, however no changes have been made as a structure change. The plugin will work well.

**Comment by chris-pb** [comment]
ok thanks for this quick answer :-)
