### ISSUE TITLE
9.2 compatibility 

### ISSUE THREAD

**Issue by chris-pb** [InfotelGLPI/certificates#13]
Hi, is the 2.2.2 version compatible with GLPI 9.2 ?

**Comment by amma35** [comment]
The certificates were introduced into the core of GLPI.

**Comment by chris-pb** [comment]
ok thank you good news !
Is there a process to import existing certificates in the core ?

**Comment by amma35** [comment]
A pre-release is out for the different tests [2.3.0-RC1](https://github.com/InfotelGLPI/certificates/releases/tag/2.3.0-RC1)

**Comment by retrack** [comment]
Hello, as there been progress on the migration with release 2.3.0? Thank you

**Comment by amma35** [comment]
A pre-release is out but no bugs back.

**Comment by retrack** [comment]
we will give it a shot ourselves too and report back here;

**Comment by b-keller** [comment]
Hi,
I tested a migration today from version 9.1.2 to 9.2.1.
I installed the version 2.3.0-RC1 without any problems ( from version 2.2.0), but  if i go to certificates in inventory menu, I see this message `Aucune donnée à migrerYou can uninstall the plugin` but no certificates in management > certificates...

how can I debug this ?

Thx

**Comment by amma35** [comment]
Hi,
If you get this message, it means that it does not find tables in the database related to the plugin.
It should be checked if in your database, you have the table 'glpi_plugin_certificates_certificates'

**Comment by b-keller** [comment]
Yes, I have this tables : 
```glpi_certificates
glpi_certificates_items
glpi_certificatetypes
glpi_plugin_certificates_certificates
glpi_plugin_certificates_certificatestates
glpi_plugin_certificates_certificates_items
glpi_plugin_certificates_certificatetypes
glpi_plugin_certificates_configs
glpi_plugin_certificates_notificationstates
```
And in the table 'glpi_plugin_certificates_certificates' there are all the certificates...

**Comment by amma35** [comment]
The migration has not been completed yet?

This message is displayed when the tables are no longer available or a session variable blocks the migration.

Have you tested to disconnect from GLPI and reconnecting to return to the "Assets"> "Certificates" menu?

**Comment by b-keller** [comment]
No,
logout and login again, doesn't do anything more.
degug mode show this query : 
```
SELECT TABLE_NAME
FROM information_schema.`TABLES`
WHERE TABLE_SCHEMA = 'glpi' AND TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE '%glpi_plugin_certificates_certificates%'
```

and post variable  ```do_migration | => | 0```

but nothing else...

**Comment by b-keller** [comment]
Hi,

If I ride up this piece of code in the begining of the certificate.php, then the migration is proposed ...

```
echo "<table align='center'><tr><td>";

   Html::showSimpleForm($_SERVER['PHP_SELF'], 'migration', __('Core migration', 'certificates'),
                        array('do_migration' => '1'),'','',
                        array(__('Are you sure you want to do core migration ??', 'certificates'),
                              __('Warning existants Certificates will be migrated !!', 'certificates')));

   echo "</td></tr></table>";

   echo "<br><span class='red b'>".__('Warning existants Certificates will be migrated !!', 'certificates')."</span>";

   echo "<br>";
```

**Comment by amma35** [comment]
Yes you will get the message because you put the message before the checks but the migration will not be done.


Do you have errors in glpi/files/_log/php-errors.log files and sql-errors.log ?

**Comment by b-keller** [comment]
Hi,

no sql-errors.log
and errors contained in php-errors.log does not seem to be related to certificate plugin : 
```
2018-01-22 11:51:20 [129@xxx.xxx.xx]
  From Toolbox::deprecated() in /var/www/html/glpi/inc/toolbox.class.php line 477
  _e() method is deprecated 
2018-01-22 11:51:20 [129@xxx.xxx.xx]
  Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/autoload.function.php:168                      Toolbox::deprecated()
  plugins/additionalalerts/setup.php:90              _e()
  inc/plugin.class.php:623                           plugin_additionalalerts_check_prerequisites()
  front/plugin.php:95                                Plugin->listPlugins()
2018-01-22 11:51:23 [129@xxx.xxx.xx]
  From Toolbox::deprecated() in /var/www/html/glpi/inc/toolbox.class.php line 477
  _e() method is deprecated 
2018-01-22 11:51:23 [129@xxx.xxx.xx]
  Backtrace :
  inc/toolbox.class.php:478                          Toolbox::backtrace()
  inc/autoload.function.php:168                      Toolbox::deprecated()
  plugins/additionalalerts/setup.php:90              _e()
  inc/plugin.class.php:623                           plugin_additionalalerts_check_prerequisites()
  front/plugin.php:95                                Plugin->listPlugins()
```

**Comment by b-keller** [comment]
so, in french, it will be a bit easier !

A la ligne 40 figure les conditions de déclenchement de la migration à savoir que la table glpi_plugins_certificates_certificates existe et que la variable POST do_migration soit égal à 1.
Le problème c'est que l'on trouve ensuite dans le code déclenché si ces deux conditions sont respectées l'affichage du formulaire contenant le bouton permettant de déclencher la migration et de passer la variable POST do_migration à 1.
En effet le code ligne 43 Html:showSimpleFom(... Affiche un formulaire contenant un bouton Migrer. La variable POST do_migration ne peut donc jamais être à 1...

is it right ?

**Comment by amma35** [comment]
Très bonne remarque effectivement la condition devrait être `$_POST['do_migration'] == 0`

Voir #13

**Comment by b-keller** [comment]
Ok,

With your last commit, migration is proposed and executed directly without need to press the button... and the migration is done.
