### ISSUE TITLE
please merge translations from Transifex

### ISSUE THREAD

**Issue by p-bo** [InfotelGLPI/certificates#14]
Hi,

noticed that new version of plugin was released - unfortunatelly without
locales update from Transifex. May I ask to merge current
translations?

Thanks :)

**Comment by amma35** [comment]
We have not updated the locales because the plugin is merged in the core of GLPI.
The whole is English.

**Comment by p-bo** [comment]
I see, but even after releasing 9.3, 9.2.x line will be broadly used, from the same reason, that 9.1 was - because delay in porting plugins to compatibility with newer GLPI major version. So it would be helpful to maintain this plugin for 9.2 for some time, because there is valid use case due this.

**Comment by amma35** [comment]
Certificates are present in the GLPI core for GLPI version 9.2
