### ISSUE TITLE
Migration from plugin data to core

### ISSUE THREAD

**Issue by AHinMaine** [InfotelGLPI/certificates#15]
Hello,

I'm running GLPI 9.4.3.  Is there a migration path or tool that will help move data in the old certificates plugin tables (glpi_plugin_certificates_%) to the new core tables (glpi_certificate%)?

Thanks!

-- Andy

**Comment by ales-infotel** [comment]
Hello,
 It’s already in the plugin, but if you want to execute it in 9.4.3 you have to modify the file setup.php like the following (Line: 100):
```
function plugin_certificates_check_prerequisites()
{
   if (version_compare(GLPI_VERSION, '9.2', 'lt') || version_compare(GLPI_VERSION, '9.5', 'ge')) {
      echo __('This plugin requires GLPI >= 9.2', 'certificates');
      return false;
   }
   return true;
}
```

After that, install/update the plugin and set the right to your profile if it necessary . Then in the menu assets, you have certificate and you can migrate data wiith this button.
![Capture](https://user-images.githubusercontent.com/53440122/62469636-f7b11380-b798-11e9-845f-e1ff7abbc677.PNG)

**Comment by AHinMaine** [comment]
Thanks!  Worked perfectly.
