### ISSUE TITLE
Wrong certificate_messages creation

### ISSUE THREAD

**Issue by kabassanov** [InfotelGLPI/certificates#7]
Hi, 

I'm trying to debug this plugin and I mentioned something strange in the file  inc/certificate.class.php:
 706          if (!isset($certificates_infos[$type][$entity])) {

I think it should be: 
                if (!isset($certificate_messages[$type][$entity])) {

Could you confirm, please?

**Comment by amma35** [comment]
yes I confirm the correction.
thank you
