### ISSUE TITLE
notification

### ISSUE THREAD

**Issue by satyan01** [InfotelGLPI/certificates#8]
Hello

when the certificate is revoked a notification for expiration is sent. and notification is set to no

**Comment by kabassanov** [comment]
Hi, I think that per certificate properties are not considered actually by notification process. For instance, I've just remarked that technician and group fields are simply ignored from certificate objects...

**Comment by satyan01** [comment]
It is possible to have a fix (if certificate is revoked no notification) ?

**Comment by fbarbieu** [comment]
Hello,
We need modify .../glpi/plugins/certificates/inc/certificate.class.php file.
The are no restriction on mailing information into sql requests.


For expired certificates:

Replace:
-----
static function queryExpiredCertificates() {

      $config=new PluginCertificatesConfig();
      $notif= new PluginCertificatesNotificationState();
      
      $config->getFromDB('1');
      $delay=$config->fields["delay_expired"];

      $query = "SELECT * 
         FROM `glpi_plugin_certificates_certificates`
         WHERE `date_expiration` IS NOT NULL
         AND `is_deleted` = '0'
         AND DATEDIFF(CURDATE(),`date_expiration`) > $delay 
         AND DATEDIFF(CURDATE(),`date_expiration`) > 0 ";
      $query.= "AND `plugin_certificates_certificatestates_id` NOT IN (999999";
      $query.= $notif->findStates();
      $query.= ") ";

      return $query;
   }
-----

by:
-----
static function queryExpiredCertificates() {

      $config=new PluginCertificatesConfig();
      $notif= new PluginCertificatesNotificationState();
      
      $config->getFromDB('1');
      $delay=$config->fields["delay_expired"];

      $query = "SELECT * 
         FROM `glpi_plugin_certificates_certificates`
         WHERE `date_expiration` IS NOT NULL
         AND `is_deleted` = '0'
	 AND `mailing` = '1'
         AND DATEDIFF(CURDATE(),`date_expiration`) > $delay 
         AND DATEDIFF(CURDATE(),`date_expiration`) > 0 ";
      $query.= "AND `plugin_certificates_certificatestates_id` NOT IN (999999";
      $query.= $notif->findStates();
      $query.= ") ";

      return $query;
   }
-----


For certificates which expire:

Replace:
-----
   static function queryCertificatesWhichExpire() {

      $config=new PluginCertificatesConfig();
      $notif= new PluginCertificatesNotificationState();
      
      $config->getFromDB('1');
      $delay=$config->fields["delay_whichexpire"];
      
      $query = "SELECT *
         FROM `glpi_plugin_certificates_certificates`
         WHERE `date_expiration` IS NOT NULL
         AND `is_deleted` = '0'
         AND DATEDIFF(CURDATE(),`date_expiration`) > -$delay 
         AND DATEDIFF(CURDATE(),`date_expiration`) < 0 ";
      $query.= "AND `plugin_certificates_certificatestates_id` NOT IN (999999";
      $query.= $notif->findStates();
      $query.= ") ";

      return $query;
   }
-----

by:
-----
   static function queryCertificatesWhichExpire() {

      $config=new PluginCertificatesConfig();
      $notif= new PluginCertificatesNotificationState();
      
      $config->getFromDB('1');
      $delay=$config->fields["delay_whichexpire"];
      
      $query = "SELECT *
         FROM `glpi_plugin_certificates_certificates`
         WHERE `date_expiration` IS NOT NULL
         AND `is_deleted` = '0'
         AND `mailing` = '1'
         AND DATEDIFF(CURDATE(),`date_expiration`) > -$delay 
         AND DATEDIFF(CURDATE(),`date_expiration`) < 0 ";
      $query.= "AND `plugin_certificates_certificatestates_id` NOT IN (999999";
      $query.= $notif->findStates();
      $query.= ") ";

      return $query;
   }
-----

Franck

**Comment by amma35** [comment]
Thanks
